name: PyInstaller CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Create venv
      run: |
        python -m venv .venv
        .venv/bin/activate

    - name: Install dependencies
      run: |
        .venv/bin/activate
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install Requirements
      run: |
        .venv/bin/activate
        pip install -r requirements.txt




    - name: Build executable
      run: |
        .venv/bin/activate
        pip show customtkinter
        pyinstaller --noconfirm --onedir --windowed --add-data '/home/runner/work/space_scouter/space_scouter/.venv/lib/python3.9/site-packages:site-packages/' --add-data "cfg:cfg/" --add-data "scores:scores/" --add-data "rankings:rankings/" "main.py"

    - name: Create ZIP artifact
      run: zip -r artifact.zip dist/main

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: artifact.zip